# Generated by Django 4.2.27 on 2026-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
