from .category_model import CategoryModel
from .product_model import ProductModel
from .book_model import BookModel
from .electronics_model import ElectronicsModel
from .fashion_model import FashionModel
from .cosmetics_model import CosmeticsModel
from .toys_model import ToysModel
from .furniture_model import FurnitureModel
from .food_model import FoodModel
from .medicine_model import MedicineModel
from .pet_supplies_model import PetSuppliesModel
from .auto_parts_model import AutoPartsModel
