# Generated by Django 4.2.27 on 2026-04-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.categorymodel'),
        ),
        migrations.CreateModel(
            name='ToysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(help_text='e.g., 0-3, 3+, 12+', max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('requires_batteries', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toys_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_toys',
            },
        ),
        migrations.CreateModel(
            name='PetSuppliesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(help_text='e.g., Dog, Cat, Bird, Fish', max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('weight_limit', models.FloatField(blank=True, help_text='in kg', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_supplies_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_pet_supplies',
            },
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_medicine',
            },
        ),
        migrations.CreateModel(
            name='FurnitureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='e.g., Oak, Metal, Plastic', max_length=100)),
                ('dimensions', models.CharField(help_text='e.g., 200x150x50 cm', max_length=100)),
                ('weight_capacity', models.FloatField(blank=True, help_text='in kg', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_furniture',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('weight', models.CharField(help_text='e.g., 500g, 1kg', max_length=50)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_food',
            },
        ),
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_fashion',
            },
        ),
        migrations.CreateModel(
            name='ElectronicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('warranty', models.IntegerField(help_text='Warranty in months')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_electronics',
            },
        ),
        migrations.CreateModel(
            name='CosmeticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('skin_type', models.CharField(help_text='e.g., Dry, Oily, Sensitive, All', max_length=50)),
                ('is_organic', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_cosmetics',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_book',
            },
        ),
        migrations.CreateModel(
            name='AutoPartsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('car_model_compatibility', models.TextField(help_text='Comma separated list of compatible car models')),
                ('warranty_years', models.IntegerField(default=1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_parts_details', to='catalog.productmodel')),
            ],
            options={
                'db_table': 'catalog_auto_parts',
            },
        ),
    ]
