# Generated by Django 4.2.27 on 2026-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting (Pending processing)'), ('packing', 'Packing (Preparing your order)'), ('in_transit', 'In Transit (Shipping)'), ('delivered', 'Delivered (Successfully handed over)'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
