# Generated by Django 4.2.27 on 2026-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shipment_shipping_method_alter_shipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id_slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_fee', models.FloatField()),
                ('free_threshold', models.FloatField(blank=True, null=True)),
                ('estimated_days', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
