# Generated by Django 4.2.27 on 2026-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shippingmethod_alter_shipment_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('ready_for_pickup', 'Ready for Pickup'), ('delivering', 'Delivering'), ('completed', 'Completed (Delivered)'), ('cancelled', 'Cancelled')], default='ready_for_pickup', max_length=20),
        ),
    ]
