# Generated by Django 4.2.27 on 2026-04-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='book_id',
            new_name='product_id',
        ),
    ]
