# Generated by Django 4.2.27 on 2026-03-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_voucher_order_membership_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='max_quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='redeemed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_vouchers', to='app.voucher')),
            ],
        ),
    ]
