# Generated by Django 4.2.27 on 2026-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_voucher_is_public_voucher_max_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_confirmation', 'Pending Confirmation'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
