# Generated by Django 4.2.27 on 2026-04-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderstatuslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='book_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='book_title',
            new_name='product_name',
        ),
    ]
