# Generated by Django 4.2.27 on 2026-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_book_id_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
