# Generated by Django 4.2.27 on 2026-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='min_points_level_id',
            field=models.IntegerField(blank=True, help_text='MembershipLevel ID from user-service', null=True),
        ),
    ]
