# Generated by Django 4.2.27 on 2026-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='app_review_book_id_258df2_idx',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer_id', 'product_id')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product_id'], name='app_review_product_c800d6_idx'),
        ),
    ]
