# Generated by Django 4.2.27 on 2026-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1543004471-240a0e96bbf4?q=80&w=2670&auto=format&fit=crop', max_length=500),
        ),
    ]
